# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Overlay(object):
    def setupUi(self, Overlay):
        Overlay.setObjectName("Overlay")
        Overlay.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        Overlay.setWindowFlag(QtCore.Qt.WindowType.WindowStaysOnTopHint)
        Overlay.move(0,0)
        Overlay.resize(541, 437)
        Overlay.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame = QtWidgets.QFrame(Overlay)
        self.frame.setGeometry(QtCore.QRect(150, -6, 391, 221))
        self.frame.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-color: rgb(255, 255, 255);\n"
"border-width: 1px;\n"
"border-style: solid;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pacestters = QtWidgets.QLabel(self.frame)
        self.pacestters.setGeometry(QtCore.QRect(0, 0, 351, 51))
        self.pacestters.setStyleSheet("background-color: transparent;")
        self.pacestters.setText("")
        self.pacestters.setPixmap(QtGui.QPixmap("./RESOURCES/Letter P with phoenix concept logo.png"))
        self.pacestters.setScaledContents(True)
        self.pacestters.setObjectName("pacestters")
        self.minimize = QtWidgets.QPushButton(self.frame)
        self.minimize.setGeometry(QtCore.QRect(350, 0, 41, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(36)
        self.minimize.setFont(font)
        self.minimize.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.minimize.setObjectName("minimize")
        self.settings = QtWidgets.QFrame(self.frame)
        self.settings.setGeometry(QtCore.QRect(0, 50, 391, 171))
        self.settings.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.settings.setFrameShadow(QtWidgets.QFrame.Raised)
        self.settings.setObjectName("settings")
        self.textBrowser = QtWidgets.QTextBrowser(self.settings)
        self.textBrowser.setGeometry(QtCore.QRect(10, 10, 171, 31))
        self.textBrowser.setStyleSheet("border-width:0px;")
        self.textBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser.setObjectName("textBrowser")
        self.frame_2 = QtWidgets.QFrame(self.settings)
        self.frame_2.setGeometry(QtCore.QRect(0, 140, 391, 31))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.sendbutton = QtWidgets.QPushButton(self.frame_2)
        self.sendbutton.setGeometry(QtCore.QRect(360, 0, 28, 28))
        self.sendbutton.setStyleSheet("border-image: url(C:/Users/tamil/Downloads/Telegram-Logo-300x300.png);\n"
"background-color: transparent;")
        self.sendbutton.setText("")
        self.sendbutton.setObjectName("sendbutton")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit.setGeometry(QtCore.QRect(0, 0, 351, 31))
        self.lineEdit.setStyleSheet("color: rgb(72, 72, 72);")
        self.lineEdit.setObjectName("lineEdit")
        self.showstatusicons = QtWidgets.QCheckBox(self.settings)
        self.showstatusicons.setGeometry(QtCore.QRect(10, 40, 161, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.showstatusicons.setFont(font)
        self.showstatusicons.setStyleSheet("color: rgb(255, 255, 255);")
        self.showstatusicons.setTristate(False)
        self.showstatusicons.setObjectName("showstatusicons")
        self.mutejarvis = QtWidgets.QCheckBox(self.settings)
        self.mutejarvis.setGeometry(QtCore.QRect(10, 70, 161, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.mutejarvis.setFont(font)
        self.mutejarvis.setStyleSheet("color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(255, 255, 255);")
        self.mutejarvis.setTristate(False)
        self.mutejarvis.setObjectName("mutejarvis")
        self.showironhomeicons = QtWidgets.QCheckBox(self.settings)
        self.showironhomeicons.setGeometry(QtCore.QRect(10, 100, 201, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.showironhomeicons.setFont(font)
        self.showironhomeicons.setStyleSheet("color: rgb(255, 255, 255);")
        self.showironhomeicons.setTristate(False)
        self.showironhomeicons.setObjectName("showironhomeicons")
        self.showterminal = QtWidgets.QCheckBox(self.settings)
        self.showterminal.setGeometry(QtCore.QRect(180, 40, 161, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.showterminal.setFont(font)
        self.showterminal.setStyleSheet("color: rgb(255, 255, 255);")
        self.showterminal.setTristate(False)
        self.showterminal.setObjectName("showterminal")
        self.customsearch = QtWidgets.QCheckBox(self.settings)
        self.customsearch.setGeometry(QtCore.QRect(180, 70, 161, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.customsearch.setFont(font)
        self.customsearch.setStyleSheet("color: rgb(255, 255, 255);")
        self.customsearch.setTristate(False)
        self.customsearch.setObjectName("customsearch")
        self.exitbutton = QtWidgets.QPushButton(self.settings)
        self.exitbutton.setGeometry(QtCore.QRect(360, 100, 20, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(22)
        self.exitbutton.setFont(font)
        self.exitbutton.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: transparent;\n"
"")
        self.exitbutton.setObjectName("exitbutton")
        self.VUIlogoButton = QtWidgets.QPushButton(Overlay)
        self.VUIlogoButton.setGeometry(QtCore.QRect(-30, -20, 211, 121))
        self.VUIlogoButton.setStyleSheet("background-color: transparent; border-image: url(""./RESOURCES/VUI Logo.png)")
        self.VUIlogoButton.setText("")
        self.VUIlogoButton.setObjectName("VUIlogoButton")
        self.listenting = QtWidgets.QLabel(Overlay)
        self.listenting.setGeometry(QtCore.QRect(0, 80, 141, 131))
        self.listenting.setText("")
        self.listenting.setPixmap(QtGui.QPixmap("./RESOURCES/listen.gif"))
        self.listenting.setScaledContents(True)
        self.listenting.setObjectName("listenting")
        self.loading = QtWidgets.QLabel(Overlay)
        self.loading.setGeometry(QtCore.QRect(0, 80, 141, 131))
        self.loading.setText("")
        self.loading.setPixmap(QtGui.QPixmap("./RESOURCES/loading.gif"))
        self.loading.setScaledContents(True)
        self.loading.setObjectName("loading")
        self.speaking = QtWidgets.QLabel(Overlay)
        self.speaking.setGeometry(QtCore.QRect(0, 80, 141, 131))
        self.speaking.setText("")
        self.speaking.setPixmap(QtGui.QPixmap("./RESOURCES/speaking.gif"))
        self.speaking.setScaledContents(True)
        self.speaking.setObjectName("speaking")
        self.Terminalframe = QtWidgets.QFrame(Overlay)
        self.Terminalframe.setGeometry(QtCore.QRect(0, 220, 541, 221))
        self.Terminalframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Terminalframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Terminalframe.setObjectName("Terminalframe")
        self.vuiterminal = QtWidgets.QTextEdit(self.Terminalframe)
        self.vuiterminal.setGeometry(QtCore.QRect(0, 0, 541, 31))
        self.vuiterminal.setStyleSheet("color: rgb(255, 255, 255);")
        self.vuiterminal.setReadOnly(True)
        self.vuiterminal.setObjectName("vuiterminal")
        self.terminal = QtWidgets.QPlainTextEdit(self.Terminalframe)
        self.terminal.setGeometry(QtCore.QRect(0, 30, 541, 191))
        self.terminal.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-width: 2px;\n"
"border-style:solid;\n"
"border-color: rgb(255, 255, 255);\n"
"font: 8pt\"Tahoma\";\n"
"color: rgb(255, 255, 255);")
        self.terminal.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.terminal.setReadOnly(True)
        self.terminal.setObjectName("terminal")
        self.VUIlogoButton.raise_()
        self.frame.raise_()
        self.listenting.raise_()
        self.loading.raise_()
        self.speaking.raise_()
        self.Terminalframe.raise_()

        self.retranslateUi(Overlay)
        QtCore.QMetaObject.connectSlotsByName(Overlay)

    def retranslateUi(self, Overlay):
        _translate = QtCore.QCoreApplication.translate
        Overlay.setWindowTitle(_translate("Overlay", "Overlay"))
        self.minimize.setText(_translate("Overlay", "-"))
        self.textBrowser.setHtml(_translate("Overlay", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:700; color:#ffffff;\">Settings</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt; font-weight:700; color:#ffffff;\"><br /></p></body></html>"))
        self.lineEdit.setPlaceholderText(_translate("Overlay", "Enter the Query to search...."))
        self.showstatusicons.setText(_translate("Overlay", "Show Status Icons"))
        self.mutejarvis.setText(_translate("Overlay", "Mute JARVIS"))
        self.showironhomeicons.setText(_translate("Overlay", "Show Iron Home Icons"))
        self.showterminal.setText(_translate("Overlay", "Show Terminal"))
        self.customsearch.setText(_translate("Overlay", "Custom Search"))
        self.exitbutton.setText(_translate("Overlay", "X"))
        self.vuiterminal.setHtml(_translate("Overlay", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:700;\">VUI  TERMINAL</span></p></body></html>"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Overlay = QtWidgets.QWidget()
    ui = Ui_Overlay()
    ui.setupUi(Overlay)
    Overlay.show()
    sys.exit(app.exec_())
